---
title: "Untitled"
author: "Gaurav Gadhvi"
date: "3/21/2022"
output: html_document
---



```{r}

require(knitr)
library(ggplot2)
library(dplyr)
library(ggthemes)
library(reshape2)
library(ggrepel)

knitr::opts_knit$set(root.dir = "/projects/b1063/Gaurav/GitDemo_RStudio/")
```





```{r}

df <- read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1_hi_filt.csv", header = T)

df2_o_50 <-  read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1_hi_filt_aging_old_subset_top50.csv", header=T)
df2_y_50 <- read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1_hi_filt_aging_young_subset_top50.csv", header=T)

df2_o <-  read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1_hi_filt_agingsig_old.csv", header=T)
df2_y <- read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1_hi_filt_agingsig_young.csv", header=T)

atac1hifilt_annotate <- read.csv("/projects/b1063/Gaurav/GitDemo_Quest/atac1hifilt_annotate.txt", sep = "\t", header = T)

df["Gene_Name"] <- atac1hifilt_annotate$Gene.Name


```



```{r}

### Plot the scatter

ggplot(df, aes(x = log2(y + 1), y = log2(o + 1), label = Gene_Name)) +
  geom_point(color = case_when(df$Peaks %in% df2_o$Peaks ~ "#595959",
                               df$Peaks %in% df2_y$Peaks ~ "#FF8000",
                               TRUE ~ "#000000"), size = 2 , alpha = 0.6)

```

